# Generated by Django 2.1.7 on 2019-07-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
